/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "التوجيه المقارن",
        filterLayers: "طبقات الخرائط",
        include: "Include",
        leftRight: "يسار/يمين",
        mapLoading: "الطبقة الخرائطية",
        refreshLayers: "طبقات التجديد",
        topBottom: "أعلى/أسفل",
        layerSelections: "طبقات الاختيار لكل جانب من جوانب المقارنة",
        layers: "الطبقات",
        outsideScale: "خارج جدول الخرائط الحالي",
        wholeTiledLayer: "مقارنتها بطبقة ذات إطار واحد",
        _widgetLabel: "Layer Compare",
        mapSection: "الخريطة",
        selectMap: "تحديد عنصر واجهة مستخدم خريطة",
        optionsSection: "خيارات المقارنة",
        startPosition: "مركز الأسهم الأولي (%)",
        allowContextToggle: "السماح للمستعملين بأن يظهروا طبقات الخرائط المرئية الأخرى",
        startContext: "تظهر في البداية طبقات مرئية أخرى على الجانبين",
        showHelp: "عرض المساعدة والتلميح الأول",
        startLabel: "العلامة الجانبية الأولى (اختيارية)",
        endLabel: "العلامة الجانبية الثانية (اختيارية)",
        labelsHint: "ترك علامات فارغة لاستخدام اليسار/اليمين أو الأعلى/القاع في قائمة الطبقات تلقائيا.",
        availableSection: "الطبقات المتاحة",
        availabilityHint: "اختر ما يمكن لمستخدمي طبقات الخرائط أن يقارنوه لايرز مخبأة من قبل مواضع قائمة الخرائط تبقى مخبأة هنا",
        defaultSection: "الاختيارات الافتراضية (اختيارية)",
        defaultsHint: "اختر أي طبقات بداية لكل جانب المقارنات تبقى متوقفة حتى يقوم المستخدم باختيار مقارنات البداية",
        previewMap: "إربطوا جهازاً من طراز 2D وفتحوا تلك الخريطة في المبنى لاختيار الطبقات والقصورات المتاحة",
        telemetrySection: "القياس عن بعد",
        telemetryLabel: "التمكين من استخدام القياس عن بعد",
        telemetryHint: "ويستخدم نفس وحدة القياس عن بعد المشتركة التي تستخدمها النظارات التقليدية الأخرى. ولا تُرسل أي أحداث إلا إذا قامت هذه المنظمة بتشكيل وجهة قياس عن بعد.",
        settingLoadError: "لا يمكن قراءة طبقات الخرائط. افتحي الخريطة في البنّاء وحاولي إصلاح الطبقات"
      })
    }
  }
})
