/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Porovnat směr",
        filterLayers: "Filtrační mapové vrstvy",
        include: "Zahrnout",
        leftRight: "Levá / pravá",
        mapLoading: "Načítám vrstvy mapy...",
        refreshLayers: "Obnovené vrstvy",
        topBottom: "Nahoře / dole",
        layerSelections: "Vyberte vrstvy pro každou porovnávací stranu",
        layers: "Vrstvy",
        outsideScale: "Mimo aktuální měřítko mapy",
        wholeTiledLayer: "Ve srovnání s jednou dlaždicovou vrstvou",
        _widgetLabel: "Porovnat vrstvu",
        mapSection: "Mapa",
        selectMap: "Vybrat widget Mapa",
        optionsSection: "Možnosti srovnání",
        startPosition: "Počáteční dělicí pozice (%)",
        allowContextToggle: "Umožnit uživatelům zobrazit další viditelné mapové vrstvy",
        startContext: "Zpočátku zobrazovat jiné viditelné vrstvy na obou stranách",
        showHelp: "Zobrazit nápovědu a první nápovědu",
        startLabel: "První boční štítek (nepovinné)",
        endLabel: "Druhé boční označení (nepovinné)",
        labelsHint: "Štítky ponechte prázdné pro automatické použití v seznamu vrstev vlevo / vpravo nebo nahoře / dole.",
        availableSection: "Dostupné vrstvy",
        availabilityHint: "Vyberte si, které vrstvy mapy mohou uživatelé porovnat. Vrstvy ukryté u map a nastavení seznamu zůstávají skryty zde.",
        defaultSection: "Výchozí volby (nepovinné)",
        defaultsHint: "Vyberte si jakékoliv počáteční vrstvy pro každou stranu. Srovnání zůstává vypnuto, dokud uživatel nevybere Srovnání.",
        previewMap: "Připojte widget 2D mapy a otevřete mapu v staviteli pro výběr dostupných vrstev a vad.",
        telemetrySection: "Použití telemetrie",
        telemetryLabel: "Povolit telemetrii sdíleného využití",
        telemetryHint: "Používá stejný sdílený telemetrický modul jako ostatní vlastní widgety. Žádné události se neposílají, pokud tato organizace nenastavila telemetrický cíl.",
        settingLoadError: "Nedalo se číst mapové vrstvy. Otevřete mapu v staviteli a zkuste Obnovit vrstvy."
      })
    }
  }
})
