/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Compare la dirección",
        filterLayers: "capas de mapa de filtro",
        include: "Incluido",
        leftRight: "Izquierda / derecha",
        mapLoading: "Cargando capas de mapa...",
        refreshLayers: "capas de recubrimiento",
        topBottom: "Parte superior / inferior",
        layerSelections: "Elija capas para cada lado de comparación",
        layers: "Capas",
        outsideScale: "Fuera de la escala de mapa actual",
        wholeTiledLayer: "Comparado como una capa de azulejos",
        _widgetLabel: "Layer Compare",
        mapSection: "Mapa",
        selectMap: "Seleccionar un widget Mapa",
        optionsSection: "Opciones de comparación",
        startPosition: "Posición inicial de divider (%)",
        allowContextToggle: "Permitir a los usuarios mostrar otras capas de mapa visibles",
        startContext: "Mostrar inicialmente otras capas visibles en ambos lados",
        showHelp: "Mostrar Ayuda y la pista de primera ejecución",
        startLabel: "Primera etiqueta lateral (opcional)",
        endLabel: "Segunda etiqueta lateral (opcional)",
        labelsHint: "Deje las etiquetas vacías para usar Izquierda / Derecha o Parte superior / átomo en la lista de capas automáticamente.",
        availableSection: "Capas disponibles",
        availabilityHint: "Elija qué capas de mapa los usuarios pueden comparar. Las capas ocultas por la lista de capas del mapa permanecen ocultas aquí.",
        defaultSection: "Selección por defecto (opcional)",
        defaultsHint: "Elige cualquier capa inicial para cada lado. La comparación se mantiene apagada hasta que el usuario seleccione Iniciar la comparación.",
        previewMap: "Conecte un widget de mapa 2D y abra ese mapa en el constructor para elegir las capas y predeterminados disponibles.",
        telemetrySection: "Telemetría de uso",
        telemetryLabel: "Permitir la telemetría de uso compartido",
        telemetryHint: "Utiliza el mismo módulo de telemetría compartida que los otros widgets personalizados. No se envían eventos a menos que esta organización haya configurado un destino de telemetría.",
        settingLoadError: "Las capas de mapa no se pueden leer. Abra el mapa en el constructor y pruebe capas Refresh."
      })
    }
  }
})
