/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Võrdle suunda",
        filterLayers: "Filtrikaardi kihid",
        include: "Kaasake",
        leftRight: "Vasak/parem",
        mapLoading: "Kaardikihtide laadimine...",
        refreshLayers: "Värskenda kihte",
        topBottom: "Ülemine / alumine",
        layerSelections: "Iga võrdluspoole kihtide valimine",
        layers: "Kihid",
        outsideScale: "Väljaspool aktiivset kaardiskaalat",
        wholeTiledLayer: "Võrreldes ühe plaaditud kihiga",
        _widgetLabel: "Kihi võrdlemine",
        mapSection: "Kaardid",
        selectMap: "Valige kaardividin",
        optionsSection: "Võrdlusvõimalused",
        startPosition: "Jagaja esialgne positsioon (%)",
        allowContextToggle: "Võimaldab kasutajatel näidata teisi nähtavaid kaardikihte",
        startContext: "Esialgu näidatakse mõlemal küljel teisi nähtavaid kihte",
        showHelp: "Abi ja esimese käigu vihje näitamine",
        startLabel: "Esimene külgmärgis (valikuline)",
        endLabel: "Teine külgmärgis (valikuline)",
        labelsHint: "Jätta sildid tühjaks, et kihtide nimekirjas automaatselt kasutada vasakut / paremat või ülevalt / alt.",
        availableSection: "Saadaolevad kihid",
        availabilityHint: "Valige, milliseid kaardikihte kasutajad saavad võrrelda. Kihid, mis on peidetud kaardi kihiloendi seadistustega, jäävad siia varju.",
        defaultSection: "Vaikimisi valikud (valikuline)",
        defaultsHint: "Valige igale küljele algkihid. Võrdlus jääb välja, kuni kasutaja valib võrdlemise alustamise.",
        previewMap: "Ühendage 2D-kaardi vidin ja avage see kaart ehitajas, et valida saadaolevad kihid ja vaikeväärtused.",
        telemetrySection: "Telemeetria kasutamine",
        telemetryLabel: "Ühiskasutuse telemeetria lubamine",
        telemetryHint: "Kasutab sama jagatud telemeetria moodulit nagu teised kohandatud vidinad. Sündmusi ei saadeta, kui see organisatsioon pole seadistanud telemeetria sihtkohta.",
        settingLoadError: "Kaardikihtide lugemine nurjus. Avage kaart ehitajas ja proovige värskendada kihid."
      })
    }
  }
})
