/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Vertaa suuntaa",
        filterLayers: "Suodatuskarttatasot",
        include: "Sisältää",
        leftRight: "Vasen / oikea",
        mapLoading: "Ladataan karttakerroksia...",
        refreshLayers: "Päivitä kerrokset",
        topBottom: "Ylä-/alaosa",
        layerSelections: "Valitse kerrokset kullekin vertailusivulle",
        layers: "Karttatasot",
        outsideScale: "Nykyisen kartta- asteikon ulkopuolella",
        wholeTiledLayer: "Verrattuna yhtenä laattakerroksena",
        _widgetLabel: "Taso Vertaa",
        mapSection: "Kartta",
        selectMap: "Valitse kartan pienoisohjelma",
        optionsSection: "Vertailuvaihtoehdot",
        startPosition: "Alkujakajan sijainti (%)",
        allowContextToggle: "Salli käyttäjien näyttää muut näkyvät karttatasot",
        startContext: "Aluksi näyttää muita näkyviä kerroksia molemmin puolin",
        showHelp: "Näytä ohje ja ensimmäisen kierroksen vihje",
        startLabel: "Ensimmäisen puolen etiketti (valinnainen)",
        endLabel: "Toisen puolen etiketti (valinnainen)",
        labelsHint: "Jätä etiketit tyhjäksi käyttääksesi Vasenta / Oikeaa tai yläreunaa / Alareunaa kerroslistassa automaattisesti.",
        availableSection: "Käytettävissä olevat karttatasot",
        availabilityHint: "Valitse mitkä karttatasot käyttäjät voivat vertailla. Kartan kerroslistan asetusten piilotetut tasot pysyvät piilossa täällä.",
        defaultSection: "Oletusvalinnat (valinnainen)",
        defaultsHint: "Valitse kaikki lähtötasot kummallekin sivulle. Vertailu pysyy poissa kunnes käyttäjä valitsee Aloita vertailu.",
        previewMap: "Liitä 2D-kartta widget ja avaa että kartta rakentaja valita käytettävissä kerroksia ja oletusarvoja.",
        telemetrySection: "Käyttötelemetria",
        telemetryLabel: "Ota käyttöön jaetun käytön telemetria",
        telemetryHint: "Käyttää samaa jaettua telemetria moduulia kuin muut mukautetut widgetit. Mitään tapahtumia ei lähetetä, ellei tämä organisaatio ole asettanut telemetriakohdetta.",
        settingLoadError: "Karttakerroksia ei voitu lukea. Avaa kartta rakennuttajassa ja kokeile Päivitä kerroksia."
      })
    }
  }
})
