/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Comparer la direction",
        filterLayers: "Filtrer les couches de la carte",
        include: "Inclure",
        leftRight: "Gauche/droite",
        mapLoading: "Chargement des couches de carte...",
        refreshLayers: "Actualiser les calques",
        topBottom: "Haut / bas",
        layerSelections: "Choisir des couches pour chaque côté de comparaison",
        layers: "Couches",
        outsideScale: "En dehors de l'échelle de carte actuelle",
        wholeTiledLayer: "Comparé à une couche carrelée",
        _widgetLabel: "Comparaison des calques",
        mapSection: "Carte",
        selectMap: "Sélectionner un widget Carte",
        optionsSection: "Options de comparaison",
        startPosition: "Position initiale du diviseur (%)",
        allowContextToggle: "Permettre aux utilisateurs d'afficher d'autres couches de cartes visibles",
        startContext: "Afficher d'abord d'autres couches visibles des deux côtés",
        showHelp: "Afficher l'aide et le premier indice",
        startLabel: "Première étiquette latérale (facultative)",
        endLabel: "Deuxième étiquette latérale (facultative)",
        labelsHint: "Laissez les étiquettes vides pour les utiliser automatiquement.",
        availableSection: "Couches disponibles",
        availabilityHint: "Choisissez quelles couches de carte les utilisateurs peuvent comparer. Les calques cachés par les paramètres de la liste des calques restent cachés ici.",
        defaultSection: "Sélection par défaut (facultatif)",
        defaultsHint: "Choisissez les couches de départ pour chaque côté. La comparaison reste en suspens jusqu'à ce que l'utilisateur sélectionne la comparaison.",
        previewMap: "Connectez un widget 2D Map et ouvrez cette carte dans le constructeur pour choisir les calques disponibles et par défaut.",
        telemetrySection: "Télémétrie d'utilisation",
        telemetryLabel: "Activer la télémétrie à usage partagé",
        telemetryHint: "Utilise le même module de télémétrie partagée que les autres widgets personnalisés. Aucun événement n'est envoyé à moins que cette organisation n'ait configuré une destination télémétrique.",
        settingLoadError: "Les calques de cartes n'ont pas pu être lus. Ouvrez la carte dans le constructeur et essayez de rafraîchir les calques."
      })
    }
  }
})
