/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "השוואת כיוון",
        filterLayers: "שכבות מפה filter",
        include: "כולל",
        leftRight: "שמאל / ימין",
        mapLoading: "טעינת שכבות מפה...",
        refreshLayers: "שכבות מרעננים",
        topBottom: "למעלה /תחתית",
        layerSelections: "בחר שכבות לכל צד",
        layers: "שכבות",
        outsideScale: "מחוץ לגודל המפה הנוכחית",
        wholeTiledLayer: "בהשוואה לשכבה אחת",
        _widgetLabel: "שכבה השוואת",
        mapSection: "מפה",
        selectMap: "בחר ווידג'ט של מפה",
        optionsSection: "אפשרויות השוואת",
        startPosition: "מיקום הפיצול הראשוני (%)",
        allowContextToggle: "לאפשר למשתמשים להראות שכבות מפות גלויות אחרות",
        startContext: "בתחילה מופיעים שכבות גלויות אחרות בשני הצדדים",
        showHelp: "הצג עזרה והרמז הראשון",
        startLabel: "תוויות צד ראשון (אופציונלי)",
        endLabel: "תוויות צד שני (אופציונלי)",
        labelsHint: "השאירו תוויות ריקות לשימוש בשמאל / ימין או למעלה/למטה ברשימת השכבות באופן אוטומטי.",
        availableSection: "שכבות זמינות",
        availabilityHint: "בחר אילו שכבות מפות משתמשים יכולים להשוות. שכבה מוסתרת על ידי הגדרות שכבת המפה נשאר חבוי כאן.",
        defaultSection: "בחירת Default (אופציונלי)",
        defaultsHint: "בחרו כל שכבות התחלה לכל צד. ההשוואה נשארת עד שהמשתמש בוחר להתחיל השוואה.",
        previewMap: "התחברו ל- 2D Map widget ופותחים את המפה ב-Builder כדי לבחור שכבות זמינות ו- ברירת מחדל.",
        telemetrySection: "שימוש בTelemetry",
        telemetryLabel: "אפשרות לשימוש משותף",
        telemetryHint: "השתמש באותה מודול טלמטרי משותף כמו widget מותאם אישית אחרים. לא נשלחים אירועים אלא אם כן ארגון זה הגדיר יעד טלמטי.",
        settingLoadError: "לא ניתן לקרוא שכבות מפה. פתח את המפה במבנה ונסה שכבות מעודנות."
      })
    }
  }
})
