/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Összehasonlítás iránya",
        filterLayers: "Szűrőtérkép rétegek",
        include: "Tartalmazza",
        leftRight: "Bal / jobb",
        mapLoading: "Térképrétegek betöltése...",
        refreshLayers: "Új rétegek",
        topBottom: "Felső / alsó",
        layerSelections: "Válasszon rétegeket az egyes összehasonlító oldalakhoz",
        layers: "Rétegek",
        outsideScale: "Az aktuális térképskálán kívül",
        wholeTiledLayer: "Összehasonlítva egy csempe réteggel",
        _widgetLabel: "A rétegek összehasonlítása",
        mapSection: "Térkép",
        selectMap: "Térképwidget kiválasztása",
        optionsSection: "Összehasonlítási lehetőségek",
        startPosition: "Kezdeti elválasztó pozíció (%)",
        allowContextToggle: "Lehetővé teszi a felhasználók számára, hogy más látható térkép rétegek",
        startContext: "Kezdetben más látható rétegek mindkét oldalon",
        showHelp: "A Súgó és az első futási tipp megjelenítése",
        startLabel: "Első oldalsó címke (nem kötelező)",
        endLabel: "Második oldalsó címke (nem kötelező)",
        labelsHint: "Hagyja üresen a címkéket a bal / jobb vagy a felső / alsó listában automatikusan.",
        availableSection: "Rendelkezésre álló rétegek",
        availabilityHint: "Válassza ki, mely térkép rétegek felhasználók összehasonlítani. A térkép által rejtett rétegek listája beállítások itt maradnak elrejtve.",
        defaultSection: "Alapértelmezett választás (nem kötelező)",
        defaultsHint: "Válassza ki a kiindulási rétegeket mindkét oldalon. Az összehasonlítás addig marad le, amíg a felhasználó kiválasztja az összehasonlítást.",
        previewMap: "Csatlakoztassa a 2D Térkép widget, és nyissa meg a térképet az építőipari választani a rendelkezésre álló rétegek és alapértelmezések.",
        telemetrySection: "A telemetria használata",
        telemetryLabel: "A megosztott használatú telemetria engedélyezése",
        telemetryHint: "Ugyanazt a megosztott telemetriai modult használja, mint a többi egyedi widget. Nem küldünk eseményeket, hacsak a szervezet nem állított be egy telemetriai célt.",
        settingLoadError: "A térképrétegeket nem lehetett leolvasni. Nyissa meg a térképet az építőiparban, és próbálja újra rétegek."
      })
    }
  }
})
