/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Bandingkan arah",
        filterLayers: "undo-type",
        include: "Sertakan",
        leftRight: "Kiri / kanan",
        mapLoading: "Memuat lapis peta...",
        refreshLayers: "undo-type",
        topBottom: "Atas / bawah",
        layerSelections: "Pilih lapis untuk setiap sisi perbandingan",
        layers: "Layer",
        outsideScale: "Di luar skala peta saat ini",
        wholeTiledLayer: "Dibandingkan dengan satu lapis tiled",
        _widgetLabel: "undo-type",
        mapSection: "Peta",
        selectMap: "Pilih widget Peta",
        optionsSection: "Opsi perbandingan",
        startPosition: "Posisi pemecah awal (%)",
        allowContextToggle: "Memungkinkan pengguna menampilkan lapis peta lain yang tampak",
        startContext: "Pertama tampilkan lapis lain yang tampak di kedua sisi",
        showHelp: "Tampilkan Bantuan dan petunjuk first-run",
        startLabel: "Label sisi pertama (opsional)",
        endLabel: "Label sisi kedua (opsional)",
        labelsHint: "Biarkan label kosong untuk menggunakan Kiri / Kanan atau Atas / Bottom dalam daftar lapis secara otomatis.",
        availableSection: "Layer yang tersedia",
        availabilityHint: "Pilih lapis peta mana yang dapat dibandingkan dengan pengguna. Lapisan tersembunyi oleh peta layerlist pengaturan tetap tersembunyi di sini.",
        defaultSection: "Pilihan baku (opsional)",
        defaultsHint: "Pilih lapisan awal untuk setiap sisi. Perbandingan tetap off sampai pengguna memilih perbandingan Mulai.",
        previewMap: "Hubungkan sebuah widget 2D Map dan buka peta dalam pembangun untuk memilih lapisan yang tersedia dan baku.",
        telemetrySection: "Penggunaan telemetri",
        telemetryLabel: "Aktifkan telemetri penggunaan bersama",
        telemetryHint: "Menggunakan modul telemetri bersama yang sama dengan widget gubahan lain. Tidak ada peristiwa yang dikirim kecuali organisasi ini telah dikonfigurasi tujuan telemetri.",
        settingLoadError: "Lapisan peta tidak dapat dibaca. Buka peta di pembangun dan coba lapisan Refresh."
      })
    }
  }
})
