/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Confrontare la direzione",
        filterLayers: "Filtri di mappa",
        include: "Includere",
        leftRight: "Sinistra / destra",
        mapLoading: "Caricamento di livelli di mappa...",
        refreshLayers: "Strati refrigeranti",
        topBottom: "Top / inferiore",
        layerSelections: "Scegliere strati per ogni lato di confronto",
        layers: "Layer",
        outsideScale: "Fuori dalla scala della mappa attuale",
        wholeTiledLayer: "Rispetto a uno strato piastrellato",
        _widgetLabel: "Livello di confronto",
        mapSection: "Mappa",
        selectMap: "Seleziona un widget mappa",
        optionsSection: "Opzioni di confronto",
        startPosition: "Posizione iniziale del divisorio (%)",
        allowContextToggle: "Permettere agli utenti di mostrare altri livelli di mappa visibile",
        startContext: "Inizialmente mostrare altri strati visibili su entrambi i lati",
        showHelp: "Mostra aiuto e il suggerimento di prima corsa",
        startLabel: "Prima etichetta laterale (opzionale)",
        endLabel: "Etichetta secondaria (opzionale)",
        labelsHint: "Lasciare le etichette vuote per usare Sinistra / Destra o Superiore / In basso nell'elenco dei livelli automaticamente.",
        availableSection: "Layer disponibili",
        availabilityHint: "Scegli quale mappa gli utenti possono confrontare. I livelli nascosti dalle impostazioni della lista di strati della mappa rimangono nascosti qui.",
        defaultSection: "Selezioni di default (opzionale)",
        defaultsHint: "Scegli qualsiasi livello di partenza per ogni lato. Il confronto rimane spento fino a quando l'utente seleziona il confronto Start.",
        previewMap: "Collegare un widget 2D Map e aprire quella mappa nel costruttore per scegliere strati e default disponibili.",
        telemetrySection: "Telemetria di utilizzo",
        telemetryLabel: "Abilitare la telemetria di utilizzo condivisa",
        telemetryHint: "Utilizza lo stesso modulo di telemetria condiviso come gli altri widget personalizzati. Nessun evento viene inviato a meno che questa organizzazione non abbia configurato una destinazione di telemetria.",
        settingLoadError: "Gli strati della mappa non potevano essere letti. Aprire la mappa nel costruttore e provare strati Refresh."
      })
    }
  }
})
