/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "方向を比較して下さい",
        filterLayers: "フィルターマップレイヤー",
        include: "含まれるもの",
        leftRight: "左/右",
        mapLoading: "ロードマップレイヤー...",
        refreshLayers: "レイヤーをリフレッシュ",
        topBottom: "トップ / ボトム",
        layerSelections: "各比較側のレイヤーを選択",
        layers: "レイヤー",
        outsideScale: "現在の地図スケールの外側",
        wholeTiledLayer: "1つの層として比較される",
        _widgetLabel: "層の比較",
        mapSection: "マップ",
        selectMap: "マップ ウィジェットの選択",
        optionsSection: "比較オプション",
        startPosition: "初期ディバイダーの位置 (%)",
        allowContextToggle: "他の地図層を表示できるように",
        startContext: "両側の他の可視層を最初に表示して下さい",
        showHelp: "Help と first-run ヒントを表示",
        startLabel: "最初の側面のラベル(任意)",
        endLabel: "第2側面のラベル(任意)",
        labelsHint: "ラベルを空にしてレイヤーリストの左/右/上/下を自動で使用してください。",
        availableSection: "使用可能なレイヤー",
        availabilityHint: "どのマップ層のユーザーが比較できるかを選択します。 地図レイヤーリストの設定で隠されているレイヤーはここに隠されています。",
        defaultSection: "デフォルト選択(オプション)",
        defaultsHint: "各側面の開始層を選んで下さい。 比較は、ユーザーがStartの比較を選択するまでオフにとどまります。",
        previewMap: "2Dマップウィジェットを接続し、そのマップをビルダーで開くと、利用可能なレイヤーとデフォルトを選択します。",
        telemetrySection: "使用法 テレメトリー",
        telemetryLabel: "共有使用テレメトリーを有効にする",
        telemetryHint: "他のカスタムウィジェットと同じ共有テレメトリーモジュールを使用します。 この組織がテレメトリーの宛先を設定している場合を除き、イベントは送信されません。",
        settingLoadError: "地図レイヤーは読み込めない。 ビルダーのマップを開き、レイヤーをリフレッシュしてみてください。"
      })
    }
  }
})
