/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "방향 비교",
        filterLayers: "필터 맵 층",
        include: "지원하다",
        leftRight: "왼쪽 / 오른쪽",
        mapLoading: "로드 맵 레이어 ...",
        refreshLayers: "새로 고침 층",
        topBottom: "상단 / 하단",
        layerSelections: "각 비교 측을 위한 층을 선택하십시오",
        layers: "레이어",
        outsideScale: "현재 맵 스케일 외부",
        wholeTiledLayer: "1개의 도와 층과 비교해",
        _widgetLabel: "Layer 비교",
        mapSection: "맵",
        selectMap: "맵 위젯 선택",
        optionsSection: "Comparison options",
        startPosition: "Initial divider position (%)",
        allowContextToggle: "Allow users to show other visible map layers",
        startContext: "Initially show other visible layers on both sides",
        showHelp: "Show Help and the first-run hint",
        startLabel: "First side label (optional)",
        endLabel: "Second side label (optional)",
        labelsHint: "Leave labels empty to use Left / Right or Top / Bottom in the layer list automatically.",
        availableSection: "사용 가능한 레이어",
        availabilityHint: "Choose which map layers users can compare. Layers hidden by the map layer-list settings stay hidden here.",
        defaultSection: "Default selections (optional)",
        defaultsHint: "Choose any starting layers for each side. Comparison stays off until the user selects Start comparison.",
        previewMap: "Connect a 2D Map widget and open that map in the builder to choose available layers and defaults.",
        telemetrySection: "Usage telemetry",
        telemetryLabel: "Enable the shared usage telemetry",
        telemetryHint: "Uses the same shared telemetry module as the other custom widgets. No events are sent unless this organization has configured a telemetry destination.",
        settingLoadError: "Map layers could not be read. Open the map in the builder and try Refresh layers."
      })
    }
  }
})
