/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "방향 비교",
        filterLayers: "필터 맵 층",
        include: "지원하다",
        leftRight: "왼쪽 / 오른쪽",
        mapLoading: "로드 맵 레이어 ...",
        refreshLayers: "새로 고침 층",
        topBottom: "상단 / 하단",
        layerSelections: "각 비교 측을 위한 층을 선택하십시오",
        layers: "레이어",
        outsideScale: "현재 맵 스케일 외부",
        wholeTiledLayer: "1개의 도와 층과 비교해",
        _widgetLabel: "Layer 비교",
        mapSection: "맵",
        selectMap: "맵 위젯 선택",
        optionsSection: "비교 옵션",
        startPosition: "초기 분배자 위치 (%)",
        allowContextToggle: "다른 눈에 보이는 맵 레이어를 표시 할 수있는 사용자",
        startContext: "처음에는 양측에 다른 눈에 보이는 층을 보여줍니다",
        showHelp: "도움말 및 첫 번째 실행 힌트보기",
        startLabel: "(선택) 첫번째 옆 상표",
        endLabel: "(선택) 두번째 옆 상표",
        labelsHint: "라벨을 왼쪽 / 오른쪽 또는 상단 / 하단 레이어 목록에서 자동으로 사용하십시오.",
        availableSection: "사용 가능한 레이어",
        availabilityHint: "어떤 맵 레이어를 선택하여 비교할 수 있습니다. 지도 레이어 목록 설정에 의해 숨겨지은 레이어 여기에 숨겨.",
        defaultSection: "기본 선택 (선택 사항)",
        defaultsHint: "각 측을 위한 어떤 시작 층든지 선택하십시오. 비교는 사용자가 시작 비교를 선택할 때까지 유지.",
        previewMap: "2D Map 위젯을 연결하고 가능한 레이어와 기본값을 선택할 수있는 빌더의지도를 엽니 다.",
        telemetrySection: "사용법 telemetry",
        telemetryLabel: "공유 사용 telemetry 활성화",
        telemetryHint: "같은 공유 telemetry 모듈을 다른 사용자 정의 위젯으로 사용합니다. 이 조직이 원격 측정 대상을 구성하지 않는 한 이벤트가 전송되지 않습니다.",
        settingLoadError: "지도 층은 읽을 수 없습니다. 건축업자에 지도를 열고 새로 고침 층을 시도하십시오."
      })
    }
  }
})
