/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Lyginti kryptį",
        filterLayers: "Filtruoti žemėlapio sluoksnius",
        include: "Įtraukti",
        leftRight: "Kairė / dešinė",
        mapLoading: "Įkeliami žemėlapio sluoksniai...",
        refreshLayers: "Atnaujinti sluoksnius",
        topBottom: "Viršuje / apačioje",
        layerSelections: "Pasirinkite sluoksnius kiekvienai palyginimo pusei",
        layers: "Sluoksniai",
        outsideScale: "Už dabartinio žemėlapio skalės ribų",
        wholeTiledLayer: "Lyginant su vienu kojomis",
        _widgetLabel: "Lygmuo",
        mapSection: "Žemėlapis",
        selectMap: "Pasirinkti žemėlapio valdiklį",
        optionsSection: "Palyginimo galimybės",
        startPosition: "Pradinė daliklio padėtis (%)",
        allowContextToggle: "Leisti naudotojams rodyti kitus matomus žemėlapio sluoksnius",
        startContext: "Iš pradžių parodyti kitus matomus sluoksnius iš abiejų pusių",
        showHelp: "Rodyti žinyną ir pirmą kartą paleistą užuominą",
        startLabel: "Pirmoji šoninė etiketė (neprivaloma)",
        endLabel: "Antroji šoninė etiketė (neprivaloma)",
        labelsHint: "Palikite etiketes tuščias naudoti Kairėje / dešinėje arba viršutinėje / apatinėje sluoksnių sąraše automatiškai.",
        availableSection: "Galimi sluoksniai",
        availabilityHint: "Pasirinkite, kuriuos žemėlapio sluoksnius vartotojai gali palyginti. Sklypai paslėptas žemėlapio layer-sąrašas nustatymus likti paslėptas čia.",
        defaultSection: "Numatytieji pasirinkimai (pasirinktinai)",
        defaultsHint: "Pasirinkite visus pradinius sluoksnius kiekvienai pusei. Palyginimas vyksta tol, kol vartotojas pasirenka pradėti palyginimą.",
        previewMap: "Prijunkite 2D Žemėlapis valdikliui ir atidarykite tą žemėlapį statybininkas pasirinkti turimus sluoksnius ir įsipareigojimų neįvykdymo.",
        telemetrySection: "Naudojimo telemetrija",
        telemetryLabel: "Įjungti bendro naudojimo telemetriją",
        telemetryHint: "Naudoja tą patį bendrą telemetrijos modulį kaip ir kiti pasirinktiniai raštai. Renginiai nesiunčiami, jei ši organizacija nėra sukonfigūravusi telemetrijos paskirties.",
        settingLoadError: "Nepavyko perskaityti žemėlapio sluoksnių. Atidarykite žemėlapį statybininkas ir pabandykite atnaujinti sluoksnius."
      })
    }
  }
})
