/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Salīdzināt virzienu",
        filterLayers: "Filtrēt kartes slāņus",
        include: "Iekļaut",
        leftRight: "Kreisā / labā",
        mapLoading: "Ielādē kartes slāņus...",
        refreshLayers: "Atjaunot slāņus",
        topBottom: "Augšā/apakšā",
        layerSelections: "Izvēlieties slāņus katrā salīdzinājuma pusē",
        layers: "Slāņi",
        outsideScale: "Ārpus pašreizējās kartes skalas",
        wholeTiledLayer: "Salīdzinot ar vienu flīžu slāni",
        _widgetLabel: "Slānis Salīdzināt",
        mapSection: "Karte",
        selectMap: "Izvēlieties kartes logrīku",
        optionsSection: "Salīdzināšanas iespējas",
        startPosition: "Sākotnējā dalītāja pozīcija (%)",
        allowContextToggle: "Atļaut lietotājiem parādīt citus redzamos kartes slāņus",
        startContext: "Sākotnēji parādīt citus redzamus slāņus abās pusēs",
        showHelp: "Rādīt palīdzību un pirmās kārtas padomu",
        startLabel: "Pirmās puses marķējums (nav obligāti)",
        endLabel: "Otrā sāna marķējums (nav obligāti)",
        labelsHint: "Atstājiet etiķetes tukšas, lai automātiski izmantotu kreiso / labo vai augšējo / apakšējo slāni sarakstā.",
        availableSection: "Pieejamie slāņi",
        availabilityHint: "Izvēlieties kurus kartes slāņus lietotāji var salīdzināt. Kartes slāņa saraksta uzstādījumos paslēptie slāņi paliek šeit.",
        defaultSection: "Noklusētās izvēles (pēc izvēles)",
        defaultsHint: "Izvēlieties sākuma slāņus katrā pusē. Salīdzinājums paliek izslēgts, līdz lietotājs izvēlas Start salīdzinājumu.",
        previewMap: "Pievienojiet 2D Map widget un atvērt šo karti celtnieks, lai izvēlētos pieejamos slāņus un noklusējuma.",
        telemetrySection: "Telemetrijas izmantošana",
        telemetryLabel: "Ieslēgt koplietošanas telemetriju",
        telemetryHint: "Izmanto to pašu kopīgotu telemetrijas moduli kā citus pielāgotos sīkrīkus. Neviens notikums netiek nosūtīts, ja šī organizācija nav konfigurējusi telemetrijas galamērķi.",
        settingLoadError: "Nevar nolasīt kartes slāņus. Atveriet karti celtājā un mēģiniet Atsvaidzināt slāņus."
      })
    }
  }
})
