/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Richting vergelijken",
        filterLayers: "Filter kaartlagen",
        include: "Includeren",
        leftRight: "Links / rechts",
        mapLoading: "Laden van kaartlagen...",
        refreshLayers: "Lagen verversen",
        topBottom: "Boven / onder",
        layerSelections: "Lagen kiezen voor elke vergelijkingszijde",
        layers: "Lagen",
        outsideScale: "Buiten de huidige kaartschaal",
        wholeTiledLayer: "Vergeleken met één tegellaag",
        _widgetLabel: "Laagvergelijking",
        mapSection: "Kaart",
        selectMap: "Selecteer een kaart-widget",
        optionsSection: "Vergelijkingsopties",
        startPosition: "Initiële scheidingspositie (%)",
        allowContextToggle: "Gebruikers toestaan andere zichtbare kaartlagen te tonen",
        startContext: "Toon eerst andere zichtbare lagen aan beide zijden",
        showHelp: "Hulp en de eerste hint tonen",
        startLabel: "Eerste zijetiket (facultatief)",
        endLabel: "Tweede zijetiket (facultatief)",
        labelsHint: "Laat labels leeg om links/rechts of boven/onder in de laaglijst automatisch te gebruiken.",
        availableSection: "Beschikbare lagen",
        availabilityHint: "Kies welke kaartlagen gebruikers kunnen vergelijken. Lagen verborgen door de instellingen van de kaartlaaglijst blijven hier verborgen.",
        defaultSection: "Standaard selecties (facultatief)",
        defaultsHint: "Kies elke beginlaag voor elke kant. Vergelijking blijft uit totdat de gebruiker selecteert Start vergelijking.",
        previewMap: "Verbind een 2D Kaart widget en open die kaart in de bouwer om de beschikbare lagen en standaardwaarden te kiezen.",
        telemetrySection: "Gebruik telemetrie",
        telemetryLabel: "Telemetrie voor gedeeld gebruik inschakelen",
        telemetryHint: "Gebruikt dezelfde gedeelde telemetriemodule als de andere aangepaste widgets. Er worden geen gebeurtenissen verstuurd tenzij deze organisatie een telemetriebestemming heeft geconfigureerd.",
        settingLoadError: "Kaartlagen konden niet worden gelezen. Open de kaart in de bouwer en probeer lagen te vernieuwen."
      })
    }
  }
})
