/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Sammenlign retning",
        filterLayers: "Filtrer kartlag",
        include: "Inkluder",
        leftRight: "Venstre/høyre",
        mapLoading: "Laster inn kartlag...",
        refreshLayers: "Oppdater lag",
        topBottom: "Topp / bunn",
        layerSelections: "Velg lag for hver sammenligningsside",
        layers: "Lag",
        outsideScale: "Utenfor gjeldende kartskala",
        wholeTiledLayer: "Sammenlignet som ett flislagt lag",
        _widgetLabel: "Lagsammenligning",
        mapSection: "Kart",
        selectMap: "Velg et kartminiprogram",
        optionsSection: "Sammenligningsalternativer",
        startPosition: "Innledende delerposisjon (%)",
        allowContextToggle: "La brukerne vise andre synlige kartlag",
        startContext: "Vis først andre synlige lag på begge sider",
        showHelp: "Vis hjelp og den første kjørende hint",
        startLabel: "Første side etikett (valgfritt)",
        endLabel: "Andre siden etikett (valgfritt)",
        labelsHint: "La etikettene være tomme for å bruke venstre / høyre eller topp / nederst i laglisten automatisk.",
        availableSection: "Tilgjengelige lag",
        availabilityHint: "Velg hvilke kartlag brukere kan sammenligne. Lagene skjult av kartlag-liste innstillinger forblir skjult her.",
        defaultSection: "Standardvalg (valgfritt)",
        defaultsHint: "Velg alle startlag for hver side. Sammenligning holder seg unna til brukeren velger Start sammenligning.",
        previewMap: "Koble til en 2D Map widget og åpne kartet i byggmesteren for å velge tilgjengelige lag og standard.",
        telemetrySection: "Bruk telemetri",
        telemetryLabel: "Aktiver telemetri for delt bruk",
        telemetryHint: "Bruker den samme delte telemetrimodulen som de andre egendefinerte widgets. Ingen hendelser sendes med mindre denne organisasjonen har konfigurert et telemetridestinasjonssted.",
        settingLoadError: "Kartlag kan ikke leses. Åpne kartet i byggmesteren og prøv Oppdater lag."
      })
    }
  }
})
