/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Porównaj kierunek",
        filterLayers: "Warstwy mapy filtra",
        include: "Dołącz",
        leftRight: "Lewa / prawa",
        mapLoading: "Ładowanie warstw map...",
        refreshLayers: "Warstwy odświeżające",
        topBottom: "Górna / dolna",
        layerSelections: "Wybierz warstwy dla każdej strony porównania",
        layers: "Warstwy",
        outsideScale: "Poza obecną skalą mapy",
        wholeTiledLayer: "W porównaniu z jedną warstwą z płytek",
        _widgetLabel: "Porównaj warstwy",
        mapSection: "Mapa",
        selectMap: "Wybierz widżet Mapa",
        optionsSection: "Opcje porównania",
        startPosition: "Początkowa pozycja dzielnika (%)",
        allowContextToggle: "Umożliwić użytkownikom wyświetlanie innych widocznych warstw mapy",
        startContext: "Początkowo widoczne są inne warstwy po obu stronach",
        showHelp: "Pokaż pomoc i pierwszą podpowiedź",
        startLabel: "Etykieta po pierwszej stronie (opcjonalnie)",
        endLabel: "Etykieta z drugiej strony (opcjonalnie)",
        labelsHint: "Pozostawić etykiety puste, aby używać lewy / prawy lub górny / dolny na liście warstw automatycznie.",
        availableSection: "Dostępne warstwy",
        availabilityHint: "Wybierz, które warstwy mapy użytkownicy mogą porównać. Warstwy ukryte przez ustawienia layer- list mapy pozostają tutaj ukryte.",
        defaultSection: "Wybór domyślny (opcjonalny)",
        defaultsHint: "Wybierz wszystkie warstwy początkowe dla każdej strony. Porównanie pozostaje wyłączone dopóki użytkownik nie wybierze porównania Start.",
        previewMap: "Podłącz widżet mapy 2D i otwórz tę mapę w budowniczym, aby wybrać dostępne warstwy i domyślnie.",
        telemetrySection: "Telemetria użytkowa",
        telemetryLabel: "Włącz telemetrię współdzielonego użytkowania",
        telemetryHint: "Używa tego samego wspólnego modułu telemetrii, co inne niestandardowe widżety. Nie wysyła się żadnych zdarzeń, chyba że ta organizacja skonfigurowała cel telemetrii.",
        settingLoadError: "Warstwy mapy nie mogły być odczytywane. Otwórz mapę w budowniczym i spróbuj Refresh warstw."
      })
    }
  }
})
