/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Compare direção",
        filterLayers: "Filtrar camadas de mapas",
        include: "Inclua",
        leftRight: "Esquerda / direita",
        mapLoading: "Carregando camadas de mapa...",
        refreshLayers: "Atualizar as camadas",
        topBottom: "Em cima / em baixo",
        layerSelections: "Escolha camadas para cada lado de comparação.",
        layers: "Camadas",
        outsideScale: "Fora da escala atual do mapa",
        wholeTiledLayer: "Comparado com uma camada de azulejo",
        _widgetLabel: "Layer Compare",
        mapSection: "Mapa",
        selectMap: "Selecione um widget Mapa",
        optionsSection: "Opções de comparação",
        startPosition: "Posição inicial do divisor (%)",
        allowContextToggle: "Permita que os usuários mostrem outras camadas visíveis do mapa.",
        startContext: "Inicialmente mostrar outras camadas visíveis em ambos os lados",
        showHelp: "Mostre ajuda e a dica de primeira corrida.",
        startLabel: "Primeiro rótulo lateral (opcional)",
        endLabel: "Segunda etiqueta lateral (opcional)",
        labelsHint: "Deixe as etiquetas vazias para usar a esquerda / direita ou superior / inferior na lista de camadas automaticamente.",
        availableSection: "Camadas disponíveis",
        availabilityHint: "Escolha quais camadas de mapa os usuários podem comparar. Camadas escondidas pelas configurações da lista de mapas ficam escondidas aqui.",
        defaultSection: "Seleções padrão (opcional)",
        defaultsHint: "Escolha qualquer camada inicial para cada lado. A comparação fica desligada até que o usuário selecione começar a comparação.",
        previewMap: "Conecte um widget de mapas 2D e abra o mapa no construtor para escolher camadas disponíveis e padrões.",
        telemetrySection: "Telemetria de uso",
        telemetryLabel: "Active a telemetria de uso compartilhado.",
        telemetryHint: "Usa o mesmo módulo de telemetria que os outros widgets personalizados. Nenhum evento é enviado a menos que esta organização tenha configurado um destino de telemetria.",
        settingLoadError: "Camadas de mapas não podiam ser lidas. Abra o mapa no construtor e tente Atualizar camadas."
      })
    }
  }
})
