/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Comparar a direcção",
        filterLayers: "Camadas de mapas filtrantes",
        include: "Incluir",
        leftRight: "Esquerda / direita",
        mapLoading: "Carregando camadas do mapa...",
        refreshLayers: "Atualizar camadas",
        topBottom: "Superior / inferior",
        layerSelections: "Escolha camadas para cada lado de comparação",
        layers: "Camadas",
        outsideScale: "Fora da escala atual do mapa",
        wholeTiledLayer: "Comparado como uma camada de azulejos",
        _widgetLabel: "Camada Comparar",
        mapSection: "Mapa",
        selectMap: "Selecione um widget de Mapa",
        optionsSection: "Opções de comparação",
        startPosition: "Posição inicial do separador (%)",
        allowContextToggle: "Permitir que os usuários mostrem outras camadas visíveis do mapa",
        startContext: "Mostra inicialmente outras camadas visíveis em ambos os lados",
        showHelp: "Mostrar a Ajuda e a dica de primeira execução",
        startLabel: "Primeira etiqueta lateral (opcional)",
        endLabel: "Segunda etiqueta lateral (opcional)",
        labelsHint: "Deixe as etiquetas vazias para usar a esquerda / direita ou superior / inferior na lista de camadas automaticamente.",
        availableSection: "Camadas disponíveis",
        availabilityHint: "Escolha quais camadas de mapa os usuários podem comparar. Camadas escondidas pelas configurações da lista de camadas do mapa permanecem escondidas aqui.",
        defaultSection: "Seleções padrão (opcional)",
        defaultsHint: "Escolha quaisquer camadas iniciais para cada lado. A comparação fica desligada até que o usuário selecione Iniciar a comparação.",
        previewMap: "Conecte um widget de Mapa 2D e abra esse mapa no construtor para escolher camadas disponíveis e padrões.",
        telemetrySection: "Telemetria de uso",
        telemetryLabel: "Activar a telemetria de utilização partilhada",
        telemetryHint: "Usa o mesmo módulo de telemetria compartilhado que os outros widgets personalizados. Nenhum evento é enviado a menos que esta organização tenha configurado um destino de telemetria.",
        settingLoadError: "Não foi possível ler as camadas do mapa. Abra o mapa no construtor e tente Atualizar camadas."
      })
    }
  }
})
