/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Compară direcția",
        filterLayers: "Straturi de hartă filtru",
        include: "Include",
        leftRight: "Stânga / dreapta",
        mapLoading: "Încărcare straturi hartă...",
        refreshLayers: "Reîmprospătează straturile",
        topBottom: "Sus / jos",
        layerSelections: "Alegeți straturi pentru fiecare parte de comparație",
        layers: "Straturi tematice",
        outsideScale: "În afara scalei actuale a hărții",
        wholeTiledLayer: "Comparativ cu un strat de gresie",
        _widgetLabel: "Comparare plan",
        mapSection: "Hartă",
        selectMap: "Selectați un widget de hartă",
        optionsSection: "Opțiuni de comparație",
        startPosition: "Poziția inițială a separatorului (%)",
        allowContextToggle: "Permite utilizatorilor să arate alte straturi vizibile ale hărții",
        startContext: "Afișează inițial alte straturi vizibile pe ambele fețe",
        showHelp: "Arată ajutor și primul indiciu alerga",
        startLabel: "Prima etichetă laterală (opțional)",
        endLabel: "A doua etichetă laterală (opțional)",
        labelsHint: "Lăsați etichetele goale pentru a utiliza stânga / dreapta sau sus / jos în lista de straturi automat.",
        availableSection: "Straturi tematice disponibile",
        availabilityHint: "Alegeți care hartă straturi utilizatorii pot compara. Straturile ascunse de setările de pe hartă rămân ascunse aici.",
        defaultSection: "Selecții implicite (opțional)",
        defaultsHint: "Alegeți orice straturi de pornire pentru fiecare parte. Comparaţia rămâne închisă până când utilizatorul selectează comparaţia Start.",
        previewMap: "Conectați un widget Harta 2D și deschideți harta în constructor pentru a alege straturi disponibile și implicite.",
        telemetrySection: "Utilizarea telemetriei",
        telemetryLabel: "Activează telemetria de utilizare comună",
        telemetryHint: "Folosește același modul de telemetrie comun ca și celelalte widget-uri personalizate. Nu sunt trimise evenimente cu excepția cazului în care această organizație a configurat o destinație telemetrie.",
        settingLoadError: "Straturile hărții nu au putut fi citite. Deschideți harta în constructor și încercați straturi Refresh."
      })
    }
  }
})
