/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Porovnať smer",
        filterLayers: "Filtrovať vrstvy mapy",
        include: "Zahrnúť",
        leftRight: "Ľavá / pravá",
        mapLoading: "Načítavam vrstvy mapy...",
        refreshLayers: "Obnoviť vrstvy",
        topBottom: "Hore/dole",
        layerSelections: "Vyberte vrstvy pre každú porovnávaciu stranu",
        layers: "Vrstvy",
        outsideScale: "Mimo aktuálnej mierky mapy",
        wholeTiledLayer: "Porovnané ako jedna naklonená vrstva",
        _widgetLabel: "Porovnať vrstvu",
        mapSection: "Mapa",
        selectMap: "Vyberte mapový widget",
        optionsSection: "Možnosti porovnania",
        startPosition: "Počiatočná poloha deliča (%)",
        allowContextToggle: "Povoliť používateľom zobraziť ďalšie viditeľné mapové vrstvy",
        startContext: "Spočiatku zobraziť ďalšie viditeľné vrstvy na oboch stranách",
        showHelp: "Zobraziť nápovedu pomoci a prvý pokus",
        startLabel: "Štítok na prvej strane (nepovinné)",
        endLabel: "Druhé bočné označenie (nepovinné)",
        labelsHint: "V zozname vrstiev nechajte etikety prázdne a použite ich vľavo / vpravo alebo hore / dole.",
        availableSection: "Dostupné vrstvy",
        availabilityHint: "Vyberte, ktoré mapové vrstvy môžu používatelia porovnať. Vrstvy skryté nastaveniami mapového zoznamu zostávajú skryté tu.",
        defaultSection: "Štandardné výbery (nepovinné)",
        defaultsHint: "Vyberte všetky počiatočné vrstvy pre každú stranu. Porovnanie zostáva vypnuté, kým užívateľ nevyberie porovnanie Štart.",
        previewMap: "Pripojte 2D Mapový widget a otvorte, že mapa v staviteľovi vybrať dostupné vrstvy a predvolené.",
        telemetrySection: "Využitie telemetrie",
        telemetryLabel: "Povoliť telemetriu zdieľaného používania",
        telemetryHint: "Používa rovnaký zdieľaný telemetrický modul ako ostatné vlastné widgety. Žiadne udalosti sa nepošlú, ak táto organizácia nenakonfigurovala cieľ telemetria.",
        settingLoadError: "Mapové vrstvy nebolo možné prečítať. Otvorte mapu v staviteľovi a skúste Obnoviť vrstvy."
      })
    }
  }
})
