/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Primerjaj smer",
        filterLayers: "Filtriraj plasti zemljevida",
        include: "Vključi",
        leftRight: "Levo/desno",
        mapLoading: "Nalaganje plasti zemljevida...",
        refreshLayers: "Osveži plasti",
        topBottom: "Zgoraj/na dnu",
        layerSelections: "Izberite plasti za vsako stran primerjave",
        layers: "Sloji",
        outsideScale: "Zunaj trenutne lestvice zemljevida",
        wholeTiledLayer: "V primerjavi z eno plastjo",
        _widgetLabel: "Primerjava plasti",
        mapSection: "Karta",
        selectMap: "Izberi pripomoček karta",
        optionsSection: "Možnosti primerjave",
        startPosition: "Začetni položaj delilnika (%)",
        allowContextToggle: "Dovoli uporabnikom, da prikažejo druge vidne plasti zemljevida",
        startContext: "Sprva prikazuje druge vidne plasti na obeh straneh",
        showHelp: "Prikaži pomoč in prvi namig",
        startLabel: "Prva stranska oznaka (neobvezno)",
        endLabel: "Druga stranska oznaka (neobvezno)",
        labelsHint: "Pustite oznake prazne, da samodejno uporabite levo / desno ali zgornjo / spodnjo stran seznama slojev.",
        availableSection: "Razpoložljivi sloji",
        availabilityHint: "Izberite, katere plasti zemljevida lahko primerjate. Plasti, skrite z nastavitvami seznama plasti zemljevida, ostanejo skrite tukaj.",
        defaultSection: "Privzete izbire (neobvezno)",
        defaultsHint: "Izberite vse začetne plasti za vsako stran. Primerjava se nadaljuje, dokler uporabnik ne izbere začetne primerjave.",
        previewMap: "Povežite gradnik 2D Map in odprite zemljevid v graditelju, da izberete razpoložljive plasti in privzete.",
        telemetrySection: "Telemetrija uporabe",
        telemetryLabel: "Omogoči telemetrijo skupne uporabe",
        telemetryHint: "Uporablja isti modul za skupno telemetrijo kot drugi gradniki po meri. Noben dogodek ni poslan, razen če ta organizacija ni nastavila cilja telemetrije.",
        settingLoadError: "Plasti zemljevida niso mogli brati. Odprite zemljevid v graditelju in poskusite Osveži plasti."
      })
    }
  }
})
