/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Jämför riktning",
        filterLayers: "Filter kartlager",
        include: "Inkludera",
        leftRight: "Vänster/höger",
        mapLoading: "Ledande kartlager...",
        refreshLayers: "Refresh lager",
        topBottom: "Top / botten",
        layerSelections: "Välj lager för varje jämförelsesida",
        layers: "Lager",
        outsideScale: "Utanför den nuvarande kartskalan",
        wholeTiledLayer: "Jämfört som ett kakelskikt",
        _widgetLabel: "Layer jämför",
        mapSection: "Karta",
        selectMap: "Välj en kartwidget",
        optionsSection: "Jämförelsealternativ",
        startPosition: "Inledande dividerposition (%)",
        allowContextToggle: "Låt användare visa andra synliga kartlager",
        startContext: "Inledningsvis visar andra synliga lager på båda sidor",
        showHelp: "Visa hjälp och den första antydan",
        startLabel: "Första sidan etiketten (valfritt)",
        endLabel: "Andra sidan etiketten (valfritt)",
        labelsHint: "Lämna etiketter tomma för att använda Vänster / Höger eller Top / Bottom i lagerlistan automatiskt.",
        availableSection: "Tillgängliga lager",
        availabilityHint: "Välj vilka kartlager användare kan jämföra. Layers dolda av map lager-list inställningarna förbli dolda här.",
        defaultSection: "Standardval (valfritt)",
        defaultsHint: "Välj alla startskikt för varje sida. Jämförelse stannar tills användaren väljer Start jämförelse.",
        previewMap: "Anslut en 2D Map widget och öppna den kartan i byggaren för att välja tillgängliga lager och standarder.",
        telemetrySection: "Använd telemetri",
        telemetryLabel: "Möjliggöra den delade användningen telemetri",
        telemetryHint: "Använder samma delade telemetrimodul som de andra anpassade widgets. Inga händelser skickas om inte denna organisation har konfigurerat en telemetri destination.",
        settingLoadError: "Kartlager kunde inte läsas. Öppna kartan i byggaren och prova rena lager."
      })
    }
  }
})
