/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "Karşılaştırma yönü",
        filterLayers: "Filtre Haritası",
        include: "Add Add Add Add Add",
        leftRight: "Sol / sağ",
        mapLoading: "Yükleniyor harita katmanları...",
        refreshLayers: "Yeni katmanlar",
        topBottom: "Top / alt",
        layerSelections: "Her karşılaştırma tarafı için katmanları seçin",
        layers: "Katmanlar",
        outsideScale: "Mevcut harita ölçeği dışında",
        wholeTiledLayer: "Bir karot tabaka olarak karşılaştırıldığında",
        _widgetLabel: "Katman Karşılaştırma",
        mapSection: "Harita",
        selectMap: "Bir Harita aracı seç",
        optionsSection: "Karşılaştırma seçenekleri",
        startPosition: "İlk bölme pozisyonu (%)",
        allowContextToggle: "Kullanıcıların diğer görünür harita tabakalarını göstermesine izin verin",
        startContext: "Başlangıçta her iki tarafta diğer görünür katmanları gösterir",
        showHelp: "Yardım ve ilk bilinen ipucu",
        startLabel: "İlk yan etiket (isteğenim)",
        endLabel: "İkinci yan etiket (isteğenim)",
        labelsHint: "Doğrudan / Doğru veya Top / Altı katman listesinde otomatik olarak kullanmak için etiket bırakın.",
        availableSection: "Kullanılabilir katmanlar",
        availabilityHint: "Hangi harita katmanı kullanıcılarının karşılaştırılabileceğini seçin. Harita katmanı liste ayarları tarafından gizlenmiş katmanlar burada saklı kalıyor.",
        defaultSection: "Varsayılan seçimler (isteğenim)",
        defaultsHint: "Her taraf için herhangi bir başlangıç katmanı seçin. Karşılaştırma kullanıcı başlangıç karşılaştırmasına kadar kapalı kalır.",
        previewMap: "2D Map widget'ı bağlayın ve mevcut katmanları ve varsayılanları seçmek için bu haritayı açın.",
        telemetrySection: "Kullanım telemetri",
        telemetryLabel: "Paylaşılan kullanım telemetrisi",
        telemetryHint: "Diğer özel pencereler olarak aynı paylaşılan telemetri modülü kullanın. Bu organizasyon bir telemetri destinasyonunu yapılandırdığı sürece hiçbir olay gönderilir.",
        settingLoadError: "Harita katmanları okunamadı. Yapımda haritayı açın ve yeni katmanları deneyin."
      })
    }
  }
})
