/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "So sánh & hướng",
        filterLayers: "Lớp lọc",
        include: "Bao gồm",
        leftRight: "Trái / phải",
        mapLoading: "Đang tải các lớp sơ đồ...",
        refreshLayers: "Làm tươi các lớp",
        topBottom: "Trên/ dưới",
        layerSelections: "Chọn các lớp cho mỗi mặt so sánh",
        layers: "Lớp",
        outsideScale: "Bên ngoài tỷ lệ bản đồ hiện tại",
        wholeTiledLayer: "So sánh với lớp lát",
        _widgetLabel: "So sánh Lớp",
        mapSection: "Bản đồ",
        selectMap: "Chọn một tiện ích Bản đồ",
        optionsSection: "Tùy chọn so sánh",
        startPosition: "Vị trí phân chia ban đầu (%)",
        allowContextToggle: "Cho phép người dùng hiển thị các lớp sơ đồ nhìn thấy khác",
        startContext: "Ban đầu hiển thị các lớp nhìn thấy khác ở cả hai bên",
        showHelp: "Hiện trợ giúp và gợi ý chạy đầu",
        startLabel: "Nhãn bên đầu (tùy chọn)",
        endLabel: "Nhãn bên thứ hai (tùy chọn)",
        labelsHint: "Để nhãn trống trong danh sách lớp.",
        availableSection: "Lớp khả dụng",
        availabilityHint: "Chọn những lớp mà người dùng có thể so sánh. Các lớp bị ẩn bởi thiết lập danh sách lớp ở đây.",
        defaultSection: "Các phần chọn mặc định (tùy chọn)",
        defaultsHint: "Chọn bất kỳ lớp khởi động cho mỗi mặt. So sánh sẽ dừng lại cho đến khi người dùng chọn bắt đầu so sánh.",
        previewMap: "Kết nối một ô điều khiển sơ đồ 2 chiều và mở bản đồ đó trong người xây dựng để chọn các lớp và mặc định sẵn sàng.",
        telemetrySection: "Theo dõi sử dụng",
        telemetryLabel: "Bật trình đo sử dụng chung",
        telemetryHint: "Dùng cùng mô- đun đo từ xa với các ô điều khiển khác. Không có sự kiện nào được gửi trừ khi tổ chức này đã cấu hình một điểm đến từ xa.",
        settingLoadError: "Không thể đọc các lớp bản đồ. Mở bản đồ trong người xây dựng và thử làm tươi các lớp."
      })
    }
  }
})
