/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "比较方向",
        filterLayers: "过滤映射层",
        include: "包含",
        leftRight: "左边/ 右边",
        mapLoading: "正在装入地图层...",
        refreshLayers: "刷新层",
        topBottom: "顶/底",
        layerSelections: "为每个比较面选择图层",
        layers: "图层",
        outsideScale: "在当前地图比例之外",
        wholeTiledLayer: "比较为一个平板层",
        _widgetLabel: "图层比较",
        mapSection: "地图",
        selectMap: "选择地图微件",
        optionsSection: "比较选项",
        startPosition: "初始分隔位置(%)",
        allowContextToggle: "允许用户显示其他可见的映射层",
        startContext: "最初显示两侧的其他可见层",
        showHelp: "显示帮助和第一个运行的提示",
        startLabel: "第一个侧标签( 可选)",
        endLabel: "第二边标签( 可选)",
        labelsHint: "在图层列表中将标签空留为使用左/右或上/下自动使用.",
        availableSection: "可用图层",
        availabilityHint: "选择哪个地图层用户可以比较 。 地图层列表设置所隐藏的图层在这里继续隐藏 。",
        defaultSection: "默认选择( 可选)",
        defaultsHint: "为每一边选择任何起始层。 在用户选择 Start 比较之前, 比较不开放 。",
        previewMap: "连接一个 2D 映射部件并在构建器中打开该映射以选择可用的图层和默认值 。",
        telemetrySection: "用法遥测",
        telemetryLabel: "启用共享用途遥测",
        telemetryHint: "使用与其他自定义部件相同的共享遥测模块 。 除非该组织配置了遥测目标,否则不发送事件。",
        settingLoadError: "无法读取地图层 。 在构建器中打开地图并尝试刷新图层 。"
      })
    }
  }
})
