/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        direction: "比較方向",
        filterLayers: "过滤地圖層",
        include: "包含",
        leftRight: "左/右",
        mapLoading: "正在載入地圖層...",
        refreshLayers: "刷新層次",
        topBottom: "上/ 下",
        layerSelections: "選擇每邊比較的層次",
        layers: "圖層",
        outsideScale: "在目前的地圖比例之外",
        wholeTiledLayer: "比較為單層平面",
        _widgetLabel: "層次比對",
        mapSection: "地圖",
        selectMap: "選擇地圖 widget",
        optionsSection: "比較選項",
        startPosition: "初始分隔位置(%)",
        allowContextToggle: "允許使用者顯示其他可见的地圖層",
        startContext: "最初顯示兩邊的其他可见的層",
        showHelp: "顯示說明和首個執行的提示",
        startLabel: "第一邊標籤( 可選擇的 )",
        endLabel: "第二邊標籤( 可選擇的)",
        labelsHint: "將標籤留為空以使用左 / 右 或 上 / 下 。",
        availableSection: "可用圖層",
        availabilityHint: "選擇可以比較的地圖層 。 地圖層列表設定所隱藏的層次要在這裡隱藏 。",
        defaultSection: "預設選擇區( 可選擇的)",
        defaultsHint: "選擇每邊的任何起始層 。 在使用者選擇開始比對之前不要做比對 。",
        previewMap: "連接 2D 地圖元件, 在建構器中開啟地圖以選擇可用的層面與預設值 。",
        telemetrySection: "用法遥測",
        telemetryLabel: "啟用共享用法遥测",
        telemetryHint: "使用與其它自訂元件相同的共享遥測模組 。 除非這個組織設定了遥測目的地, 任何事件都無法傳送 。",
        settingLoadError: "無法讀取地圖層 。 在建構器中開啟地圖並試圖刷新層面 。"
      })
    }
  }
})
